# Generated by Django 5.2.17 on 2026-09-11 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('category', models.CharField(choices=[('Compute', 'Compute'), ('Storage', 'Storage'), ('Network', 'Network'), ('Dataset', 'Dataset'), ('Service', 'Service'), ('Other', 'Other')], max_length=20, null=True)),
                ('capacity_units', models.PositiveIntegerField(default=0, null=True, verbose_name='Total Capacity')),
                ('allocated_units', models.PositiveIntegerField(default=0, null=True, verbose_name='Allocated Capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Database Resource',
                'verbose_name_plural': 'Database Resources',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_units', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('EXECUTING', 'Executing'), ('COMMITTED', 'Committed'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='CREATED', max_length=20, verbose_name='Transaction State')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.databaseresource', verbose_name='Database Resource')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Transaction Operator')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='dashboard.databasetransaction')),
            ],
            options={
                'verbose_name': 'Transaction Audit Entry',
                'verbose_name_plural': 'Transaction Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
